-- 1. Create the users table
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL
);

-- 2. Create the custom_civilizations table
CREATE TABLE IF NOT EXISTS public.custom_civilizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    start_year INTEGER,
    end_year INTEGER,
    region TEXT,
    resource_density DOUBLE PRECISION,
    knowledge_density DOUBLE PRECISION,
    military_strength DOUBLE PRECISION,
    added_by_id BIGINT,
    CONSTRAINT custom_civilizations_added_by_id_fkey FOREIGN KEY (added_by_id) REFERENCES public.users (id)
);
